[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "apairo-rr"
version = "0.1.0"
description = "Rerun-based LiDAR visualisation for apairo datasets"
authors = [
  { name = "Augustin Bresset", email = "augustin.bresset@gmail.com" },
]
license = { text = "MIT" }
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "rerun-sdk",
    "PyYAML",
    "apairo @ git+https://github.com/apairo-robotics/apairo.git",
    "apairo-preprocess @ git+https://github.com/apairo-robotics/apairo_preprocess.git",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["."]
include = ["apairo_rr*"]

[tool.setuptools.package-data]
apairo_rr = ["configs/*.yaml"]
